[
project
]
project_name = "snowops"
version = "0.1.0"
description = "A Python project using streamlit to govern, monitor and observe Snowflake DataOps"
authors = ["Thiago Dias thiago@thir.info"]
python_version = "3.8.18"

[
virtualenv
]
in_project = true
venv_name = ".venv"

[
git
]
repo_url = "https://github.com/Thealdersonproject/snowops.git"
initial_branch = "main"