[
python1.
]
version = "3.11"

[
project
]
name = ""
version = "0.1.0"
description = ""

[
authors
]
author = "Thiago Dias - thiago@thir.info - www.thir.info"

[
requirements
]

[
requirements-dev
]
poetry = "==1.8.4"
poetry-core = "==1.9.1"
pytest = "==6.2.5"
pre-commit = "==3.8.0"
black = "==24.8.0"
isort = "==5.13.2"
flake8 = "==7.1.1"
pylint = "==3.2.6"
mypy = "==1.11.2"
types-toml = "==0.10.8.20240310"

[
git
]
url = ""
branch = ""
user = ""
